include ../../plugin_defs

OBJS = $(OBJDIR)/comprmulti.o \
	$(OBJDIR)/comprmultigui.o

PLUGIN = compressormulti

include ../../plugin_config

$(OBJDIR)/compressor.o: comprmulti.C
$(OBJDIR)/compressorgui.o: comprmultigui.C
