include ../../plugin_defs

OBJS = \
	$(OBJDIR)/timeblur.o \
	$(OBJDIR)/timeblurwindow.o

PLUGIN = timeblur

include ../../plugin_config

$(OBJDIR)/timeblur.o: timeblur.C
$(OBJDIR)/timeblurwindow.o: timeblurwindow.C
