include ../../plugin_defs

OBJS = $(OBJDIR)/colorspace.o  \
	$(OBJDIR)/colorspacewindow.o

PLUGIN = colorspace

include ../../plugin_config

$(OBJDIR)/colorspace.o: colorspace.C
$(OBJDIR)/colorspacewindow.o: colorspacewindow.C

