#ifndef __COMPRESSORTOOLS_INC__
#define __COMPRESSORTOOLS_INC__

class BandConfig;
class CompressorConfigBase;
class CompressorClientFrame;
class CompressorFreqFrame;
class CompressorGainFrame;
class CompressorEngine;
class CompressorCopy;
class CompressorPaste;
class CompressorClearGraph;
class CompressorPopup;

#define GRAPH_BG_COLOR		0x559977
#define GRAPH_BORDER1_COLOR	0xeeaa44
#define GRAPH_BORDER2_COLOR	0xeeaaff
#define GRAPH_GRID_COLOR	0xeeffcc
#define GRAPH_ACTIVE_COLOR	0x99cc77
#define GRAPH_INACTIVE_COLOR	0x666688

#endif
