
/*
 * CINELERRA
 * Copyright (C) 2008 Adam Williams <broadcast at earthling dot net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#ifndef RECORDGUI_INC
#define RECORDGUI_INC

class RecordGUIBatches;
class RecordGUI;
class RecordGUISave;
class RecordGUICancel;
class RecordGUIOK;
class RecordGUIStartBatches;
class RecordGUIStopBatches;
class RecordGUIActivateBatch;
class RecordGUIStartOver;
class EndRecordThread;
class RecordStartoverThread;
class RecordBatch;
class RecordPath;
class RecordStart;
class RecordDuration;
class RecordSource;
class RecordNews;
class RecordGUIDropFrames;
class RecordGUIFillFrames;
class RecordGUIPowerOff;
class RecordGUICommCheck;
class RecordGUIDelaceItem;
class RecordGUIDeinterlace;
class RecordGUIMonitorVideo;
class RecordGUIMonitorAudio;
class RecordGUIAudioMeters;
class RecordGUINewBatch;
class RecordGUIDeleteBatch;
class RecordGUILabel;
class RecordGUIClearLabels;
class RecordStatusThread;
class RecordGUIFlash;
class RecordGUIModeMenu;
class RecordGUIModeTextBox;
class RecordGUIModeListBox;
class RecordGUIModeMenu;
class RecordGUIDCOffset;
class RecordGUIDCOffsetText;
class RecordGUIReset;
class RecordGUIResetTranslation;
class RecordMonitor;

#endif
