#ifndef __SWINDOW_INC__
#define __SWINDOW_INC__

class SWindow;
class SWindowOK;
class SWindowCancel;
class SWindowLoadPath;
class SWindowLoadFile;
class SWindowSaveFile;
class SWindowItemFormat;
class SWindowSaveFormat;
class ScriptLines;
class ScriptScroll;
class ScriptPosition;
class ScriptEntry;
class ScriptPrev;
class ScriptNext;
class ScriptPaste;
class ScriptClear;
class SWindowGUI;
class SubttlSWin;

#endif
